version: '3'
services:
  web:
    build: web
    volumes:
      - ./web/apache2/:/etc/apache2
      - ./web/html:/var/www/html
    links:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/:/var/lib/mysql

  nginx: 
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
    links:
      - web

  django:
    build:
      context: ./django/app
      target: builder


